config/routes.rb
CrashUp::Application.routes.draw do
  devise_for :users do
  end
  root :to => "pages#index"

  resources :pages
  resources :tournaments do
    resources :teams
    resources :round_robins
  end

end

app/models/round_robin.rb
class RoundRobin < ActiveRecord::Base

  belongs_to :tournament
  has_many :teams, :through => :tournament
 #has_many :teams_in_play

  accepts_nested_attributes_for :tournament
  accepts_nested_attributes_for :teams

  serialize :teams_in_play


  def schedule(tournament_id)

   # @round_robin = RoundRobin.params[:id]
    #scheduled_teams.teams_in_play = params [:teams_in_play].to_a
    
    number_of_teams = Tournament.find(tournament_id).number_of_teams
    teams = Tournament.find(tournament_id), RoundRobin.find(id)
    puts "#{number_of_teams}number_of_teams"
    puts "#{teams}"
    row1 = (1..number_of_teams).map do |home_team|
        puts "#{home_team}home_team_slot"

    end

    row2 = (1..number_of_teams).map do |away_team|
        puts "#{away_team}away_team_slot"
    end 

    a = teams_in_play.permutation(2).to_a
      puts a.inspect
    
  end
  

  
end

app/models/team.rb
class Team < ActiveRecord::Base

  belongs_to :tournament
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  belongs_to :user

  has_many :teams
  
  accepts_nested_attributes_for :teams

  has_many :round_robins



  def number_of_teams_in_play
  	@number_of_teams_in_play = Tournament.last.number_of_teams
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @tournaments = Tournament.all
  	render :controller => "tournaments", :action => "index"
  end

end

app/controllers/round_robins_controller.rb
class RoundRobinsController < ApplicationController

  before_filter :populate, :only => [:show, :index]

  
  def populate
     @tournament = Tournament.find(params[:tournament_id])
     @round_robin_teams = @tournament.teams.all
     @current_round_robin_teams = @round_robin_teams.shuffle
     @teams_in_play = @current_round_robin_teams

  end

  def index

  end

  def new
    @tournament = Tournament.find(params[:tournament_id])
    @round_robin.teams_in_play = @tournament.teams.all
    @round_robin = RoundRobin.new
  end

  def show

    @tournament = Tournament.find(params[:tournament_id])    
    @round_robin = RoundRobin.find(params[:id])
    @current_round_robin_teams =  @round_robin.teams_in_play.map {|team| Team.find(team.to_i) }
    #@round_robin_teams = @round_robin.teams.all
    @round_robin_schedule = @round_robin.schedule(@tournament.id)
    
    
#    @round_robin_schedule_generator = @round_robin.generator
    

  end

  def create
    puts "hello create"
    puts params[:teams_in_play]
#    puts params[:round_robin]
#    puts params[:number_of_teams]
    @tournament = Tournament.find(params[:tournament_id])
    #populate
    @round_robin = RoundRobin.new(params[:round_robin_id])
    @round_robin.teams_in_play  = params[:teams_in_play]
    #@round_robin = @round_robin.teams_in_play  
    @round_robin.save
    puts "Saved"
    #@current_round_robin_teams.save
  #  flash[:success] = "Here it is"
    redirect_to tournament_round_robin_path(@tournament, @round_robin)
  end



  def round_robin_params
    params.require(:round_robin).permit(:teams_in_play)
  end

end
#permit( :id, :name, people_attributes: [:id, :email, :password, :password_confirmation] )
#  end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @tournament = Tournament.find(params[:tournament_id])   
#  	@teams_count = @tournament.number_of_teams_in_play
    @teams_in_play_list = @tournament.teams.all
  end

  def show
    @tournament = Tournament.find(params[:tournament_id])    
  	@team = Team.find(params[:id])
  end

  def new
    @tournament = Tournament.find(params[:tournament_id])
    @team = Team.new	
  end



  def create
    @tournament = Tournament.find(params[:tournament_id])
  	@team = @tournament.teams.new(team_params)
	  if @team.save
  	  flash[:success] = "Added Team"
  	  redirect_to tournament_teams_path
	  else
  	  render :new
	  end
  end

  private

#  def tournament_params
#    params.require(:tournament).permit(:name, :number_of_teams, :id)
#  end

  def team_params
    params.require(:team).permit(:name)
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def index
    @tournaments = Tournament.all
    @tournament.created_by = Tournament.where(:user_id => current_user)
  end

  def new
  	@tournament = Tournament.new
  end

  def create
  	@tournament = Tournament.new(tournament_params)
    @tournament.created_by = current_user
    @tournament.user_email = User.find(current_user.id).email
	    if @tournament.save
  	    flash[:success] = "Made a new tournament"
  	    redirect_to @tournament
	    else
  	    render :new
	    end
  end

  def show
    @tournament = Tournament.find(params[:id])
  end

  def edit
    @tournament = Tournament.find(params[:id])
  end

  def update
    @tournament = Tournament.find(params[:id])
    @tournament.update(tournament_params)
  end


  def tournament_params
    params.require(:tournament).permit(:name, :number_of_teams, :id, :created_by, :user_email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
  	User 
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/round_robins_helper.rb
module RoundRobinsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrashUp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>
	   <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

</body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>





<% if user_signed_in? %>
  <div>Hello <%= current_user.email %> pick your tournament</div>
  <div id="sign_in"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></div>
<% else %>

<h1>welcome</h1>

<div id="sign_in">
  <%= link_to "New", new_user_registration_path, :method => :get %>
  <%= link_to "Sign in", new_user_session_path, :method => :get %>
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
</div>


<% end %>

<%= render template:"tournaments/index" %>

app/views/round_robins/_form.html.erb
<%= form_for (@round_robin) do |f| %>

  <div class="field">
  	<%= f.label :teams_in_play %><br />
  	<%= f.text_field :teams_in_play %>
  </div>
  <%= f.submit %>

<% end %>

app/views/round_robins/index.html.erb
<p>RR index</p>

<% @current_round_robin_teams.map do |team| %>
      <li>
        <%= team.name %>
      </li>

<% end %>
<%= link_to "Create the Round Robin", tournament_round_robins_path(@tournament, @team, :teams_in_play => @current_round_robin_teams),:method => "post" %>

app/views/round_robins/new.html.erb
<h1>Round Robin</h1>

<%= render 'form' %>

app/views/round_robins/show.html.erb
<h1>show round robin teams</h1>
    
  <ul class="round_robin_teams">
    <% @current_round_robin_teams.each do |team| %>
      <li>
        <%= team.name %>
      </li>

    <% end %>

  </ul>


  <%= @round_robin_schedule %>

app/views/tournaments/_form.html.erb
<%= form_for(@tournament) do |f| %>

<ul>
  <li>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
  	</div>
  </li>

  <li>
    <div class="field">
      <%= f.label :number_of_teams %><br />
      <%= f.text_field :number_of_teams %>
  	</div>
  </li>



  <%= f.submit %>
</ul>
<% end %>

app/views/tournaments/edit.html.erb
<%= render 'form' %>

app/views/tournaments/index.html.erb
<h1>Current Tournament List</h1>

  <ul>
    <% @tournaments.each do |tournaments| %>
      <li>
        <%= tournaments.name %>

      </li>
    <% end %>

  </ul>

  

<%= link_to "new tournament", new_tournament_path %>

app/views/tournaments/new.html.erb
<h1>New Tournament</h1>

<% if user_signed_in? %>
  <%= render 'form' %>
<% else %>
  <P>You need to sign in to create a tournament</p>
  <%= link_to "Sign in", new_user_session_path, :method => :get %>
<% end %>

app/views/tournaments/show.html.erb
h1>Tournament Show</h1>

<%= @tournament.name %>

<br/>

<%= @tournament.number_of_teams %>

<br/>


	

<%= link_to 'Add a Team', new_tournament_team_path(@tournament) %>

<ul>
  <li>

  </li>

</ul>

app/views/tournaments/update.html.erb
<%= link_to "need fixin", edit_tournament_path %>
<%= link_to "look good?", tournament_path %>